version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-root-password
      MYSQL_DATABASE: ruby-profiler-database
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
